project:
  type: website
  output-dir: docs

website:
  title: "Rachel Bouwer"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About Me

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



